image: docker:git

services:
  - docker:dind

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper

gradle-build:
  stage: build
  image: openjdk:14-jdk
  script: "./gradlew build -x test"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CI_REGISTRY_IMAGE:$(git describe --tags) -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$(git describe --tags)

docker-build-staging:
  stage: package
  only:
    - staging
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE:staging || true
    - docker build --cache-from $CONTAINER_IMAGE:staging -t $CI_REGISTRY_IMAGE:$(git describe --tags)-staging -t $CI_REGISTRY_IMAGE:staging .
    - docker push $CI_REGISTRY_IMAGE:staging
    - docker push $CI_REGISTRY_IMAGE:$(git describe --tags)-staging
