spring:
  mail:
    default-encoding: UTF-8
    host: localhost
    username: foo
    password: bar
    port: 1025
    default-sender: "tester@encircle360.com"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false