spring:
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST:""}
    username: ${SMTP_USER:""}
    password: ${SMTP_PASSWORD:""}
    port: ${SMTP_PORT:587}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  freemarker:
    template-loader-path:
      - file:/resources/templates
      - classpath:templates