spring:
  application:
    name: straightmail
  data:
    mongodb:
      uri: mongodb://localhost:27017/straightmail
      database: straightmail
      host: localhost
      port: 2701
  mail:
    host: localhost
    username: foo
    password: bar
    port: 1025
    default-sender: "tester@encircle360.com"
    default-template: "default"
  freemarker:
    template-loader-path:
      - classpath:templates

#debug: true
