spring:
  application:
    name: straightmail
  data:
    mongodb:
      uri: mongodb://localhost:27017/straightmail
      database: straightmail
      host: localhost
      port: 2701
  mail:
    default-encoding: UTF-8
    host: localhost
    username: foo
    password: bar
    port: 1025
    default-sender: "tester@encircle360.com"
    default-template: "default"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${SMTP_ENABLE_TLS:false}
          ssl:
            enable: ${SMTP_ENABLE_SSL:false}
    protocol: smtp
    test-connection: false
  freemarker:
    template-loader-path:
      - classpath:templates

#debug: true
